let express= require("express")
let {add,login, getpost, getpostbycat, updpost, delpost, addpost, addwish, getwish, getuser} = require("../controller/rescont")
let route = express.Router()
route.post("/login",login)
route.post("/reg",add)
route.post("/add",addpost)
route.get("/getpost",getpost)
route.get("/getuser",getuser)
route.get("/getbycat/:cat/:value",getpostbycat)
route.post("/upd",updpost)
route.delete("/del/:_id",delpost)
route.post("/wladd",addwish)
route.get("/getwish/:id",getwish)
module.exports = route